"""add position to invitations

Revision ID: 605017d1ae58
Revises: ebbd01cc51b0
Create Date: 2026-04-03 11:04:50.388019
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605017d1ae58'
down_revision: Union[str, None] = 'ebbd01cc51b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'position')
    # ### end Alembic commands ###
