"""add phone_public to users

Revision ID: 7200d467c98b
Revises: 605017d1ae58
Create Date: 2026-04-03 15:13:02.173694
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7200d467c98b'
down_revision: Union[str, None] = '605017d1ae58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_public')
    # ### end Alembic commands ###
