"""add magic_tokens invite_links tables and invited_by_id

Revision ID: ebbd01cc51b0
Revises: c1161363fcb0
Create Date: 2026-04-03 10:52:23.790026
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbd01cc51b0'
down_revision: Union[str, None] = 'c1161363fcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('ratking_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ratking_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_links_code'), 'invite_links', ['code'], unique=True)
    op.create_table('magic_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_tokens_token'), 'magic_tokens', ['token'], unique=True)
    op.add_column('users', sa.Column('invited_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['invited_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invited_by_id')
    op.drop_index(op.f('ix_magic_tokens_token'), table_name='magic_tokens')
    op.drop_table('magic_tokens')
    op.drop_index(op.f('ix_invite_links_code'), table_name='invite_links')
    op.drop_table('invite_links')
    # ### end Alembic commands ###
